// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace WebTemplate.Migrations
{
    [DbContext(typeof(IspitContext))]
    [Migration("20250819154343_DodataCenaUKartu")]
    partial class DodataCenaUKartu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Karta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Cena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Placena")
                        .HasColumnType("bit");

                    b.Property<int?>("ProjekcijaID")
                        .HasColumnType("int");

                    b.Property<int>("Red")
                        .HasColumnType("int");

                    b.Property<int?>("SalaID")
                        .HasColumnType("int");

                    b.Property<int>("Sediste")
                        .HasColumnType("int");

                    b.Property<bool>("Zauzeto")
                        .HasColumnType("bit");

                    b.Property<int>("sifraProjekcije")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProjekcijaID");

                    b.HasIndex("SalaID");

                    b.ToTable("Karte");
                });

            modelBuilder.Entity("backend.Models.Projekcija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremePrikazivanja")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Projekcije");
                });

            modelBuilder.Entity("backend.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UkupanBrojRedova")
                        .HasColumnType("int");

                    b.Property<int>("UkupanBrojSedista")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("backend.Models.Karta", b =>
                {
                    b.HasOne("backend.Models.Projekcija", "Projekcija")
                        .WithMany("Karte")
                        .HasForeignKey("ProjekcijaID");

                    b.HasOne("backend.Models.Sala", "Sala")
                        .WithMany("Karte")
                        .HasForeignKey("SalaID");

                    b.Navigation("Projekcija");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("backend.Models.Projekcija", b =>
                {
                    b.Navigation("Karte");
                });

            modelBuilder.Entity("backend.Models.Sala", b =>
                {
                    b.Navigation("Karte");
                });
#pragma warning restore 612, 618
        }
    }
}
